package iti.jets.dao;
 
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher",catalog="inheritance1"
)
public class Teacher extends Person implements java.io.Serializable {


     private Integer id;
    
     private Date hireDate;

    public Teacher() {
    }

    public Teacher(Date hireDate ,String fristname ,String lastname) {
        super(fristname,lastname);
       this.hireDate = hireDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=false, length=10)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


